// src/api/gallery.ts — Gallery CRUD API functions
import { supabase } from "../../utils/supabase/client";
import { GalleryItem, GalleryCreate, GalleryUpdate, gallerySchema } from "../schemas/gallery";

// GET all gallery items with optional category filter

// Local images generated by AI
const LOCAL_GALLERY_IMAGES: GalleryItem[] = [
  {
    id: '1',
    title: 'Luxury Wedding Reception',
    image_url: '/new-gallery-images/wedding.png',
    category: 'Weddings',
    description: 'A luxurious wedding reception hall with crystal chandeliers and floral decorations.',
    event_type: 'Wedding',
    is_featured: true,
  },
  {
    id: '2',
    title: 'Corporate Conference',
    image_url: '/new-gallery-images/corporate.png',
    category: 'Corporate Events',
    description: 'Modern corporate event setup with professional lighting and seating.',
    event_type: 'Corporate',
    is_featured: true,
  },
  {
    id: '3',
    title: 'Gala Dinner',
    image_url: '/new-gallery-images/dining.png',
    category: 'Social Gatherings',
    description: 'Elegant dining arrangement for a gala dinner.',
    event_type: 'Social',
    is_featured: true,
  },
  {
    id: '4',
    title: 'Garden Party',
    image_url: '/new-gallery-images/outdoor.png',
    category: 'Social Gatherings',
    description: 'Beautiful outdoor garden party setup at sunset.',
    event_type: 'Social',
    is_featured: false,
  }
];

export const getGalleryItems = async (category?: string): Promise<GalleryItem[]> => {
  // Return local images immediately to reflect changes requested
  // In a real scenario with write access, we would fetch from DB:
  /*
  let query = supabase.from('gallery').select('*').order('created_at', { ascending: false });
  if (category) query = query.eq('category', category);
  const { data, error } = await query;
  if (error) throw new Error(error.message);
  return gallerySchema.array().parse(data || []);
  */

  let images = [...LOCAL_GALLERY_IMAGES];
  if (category) {
    images = images.filter(img => img.category === category);
  }
  return Promise.resolve(images);
};

// GET single gallery item by ID
export const getGalleryItem = async (id: string): Promise<GalleryItem> => {
  const { data, error } = await supabase
    .from('gallery')
    .select('*')
    .eq('id', id)
    .single();

  if (error) throw new Error(error.message);
  return gallerySchema.parse(data);
};

// CREATE new gallery item
export const createGalleryItem = async (galleryData: GalleryCreate): Promise<GalleryItem> => {
  const { data, error } = await supabase
    .from('gallery')
    .insert([galleryData])
    .select()
    .single();

  if (error) throw new Error(error.message);
  return gallerySchema.parse(data);
};

// UPDATE gallery item
export const updateGalleryItem = async (id: string, galleryData: GalleryUpdate): Promise<GalleryItem> => {
  const { data, error } = await supabase
    .from('gallery')
    .update(galleryData)
    .eq('id', id)
    .select()
    .single();

  if (error) throw new Error(error.message);
  return gallerySchema.parse(data);
};

// DELETE gallery item
export const deleteGalleryItem = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('gallery')
    .delete()
    .eq('id', id);

  if (error) throw new Error(error.message);
};

// React Query keys
export const galleryKeys = {
  all: ["gallery"] as const,
  lists: () => [...galleryKeys.all, "list"] as const,
  list: (filters?: any) => [...galleryKeys.lists(), filters] as const,
  details: () => [...galleryKeys.all, "detail"] as const,
  detail: (id: string) => [...galleryKeys.details(), id] as const,
};
